// Auto-generated by scripts/crawl-data.ts
// Run `npm run crawl` to populate with real data from Naver API.
// This placeholder uses empty arrays so the app falls back to default data.

import type { Restaurant, Tip, CuratedPost } from "./mock";

export const crawledRestaurants: Restaurant[] = [];

export const crawledTips: Tip[] = [];

export const crawledCurated: CuratedPost[] = [];
